import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

// --- I. Constants and Local Data ---

// English Labels
const L = {
  transactionDetails: 'Transaction Details',
  transactionId: 'Transaction ID',
  date: 'Date',
  time: 'Time',
  createdBy: 'Created By',
  customerInfo: 'Customer Information',
  name: 'Name',
  phone: 'Phone',
  email: 'Email',
  customerId: 'Customer ID',
  paymentInfo: 'Payment Information',
  paymentMethod: 'Payment Method',
  category: 'Category',
  notes: 'Additional Notes',
  invoiceId: 'Invoice ID',
  branchId: 'Branch',
  customerBank: 'Customer Bank',
  customerAccNum: 'Customer Account Number',
  bankName: 'Bank Name',
  accountNumber: 'Account Number',
  chequeNumber: 'Cheque Number',
  mobileProvider: 'Provider',
  transactionIdShort: 'Transaction ID',
  reference: 'Reference',
  debitAccount: 'Debit Account',
  creditAccount: 'Credit Account',
  bank: 'Bank',
  accountNumberLong: 'Account Number',
  footerMessage: 'This receipt has been automatically generated by the system',
  systemName: 'ERP Dashboard System',
  status: 'Status',
  amount: 'Amount',
  transactionType: 'Transaction Type',
};

// Transaction Types and their colors
const TRANSACTION_TYPES = {
  credit: {
    text: 'Credit (Income)',
    color: '#10B981', // Green
  },
  debit: {
    text: 'Debit (Expense)',
    color: '#EF4444', // Red
  },
  'account-transfer': {
    text: 'Account to Account Transfer',
    color: '#3B82F6', // Blue
  },
};

// Payment Method Map
const PAYMENT_METHODS = {
  bank: 'Bank Transfer',
  'bank-transfer': 'Bank Transfer',
  'ব্যাংক ট্রান্সফার': 'Bank Transfer',
  cheque: 'Cheque',
  'চেক': 'Cheque',
  'mobile-banking': 'Mobile Banking',
  'মোবাইল ব্যাংকিং': 'Mobile Banking',
  cash: 'Cash',
  'নগদ': 'Cash',
  card: 'Card',
  'কার্ড': 'Card',
};

// Category Map - Keep original values if they're already in English, otherwise map
const CATEGORIES = {
  hajj: 'Hajj & Umrah',
  'হাজ্জ প্যাকেজ': 'Hajj Package',
  'ওমরাহ প্যাকেজ': 'Umrah Package',
  'air-ticket': 'Air Ticket',
  'এয়ার টিকেট': 'Air Ticket',
  visa: 'Visa Service',
  'ভিসা সার্ভিস': 'Visa Service',
  hotel: 'Hotel Booking',
  'হোটেল বুকিং': 'Hotel Booking',
  insurance: 'Insurance',
  'ইনসুরেন্স': 'Insurance',
  other: 'Other Service',
  'অন্যান্য সেবা': 'Other Service',
};

// স্টাইল কনফিগারেশন ফাংশন (Dark/Light Mode)
const getStyles = (isDark) => ({
  // Color Palette
  primary: '#3B82F6', // Blue
  secondary: '#10B981', // Green
  warning: '#F59E0B', // Amber/Orange
  info: '#8B5CF6', // Violet
  
  // Background and Text
  bg: isDark ? '#1F2937' : '#FFFFFF',
  cardBg: isDark ? '#374151' : '#F9FAFB',
  textPrimary: isDark ? '#F3F4F6' : '#374151',
  textSecondary: isDark ? '#D1D5DB' : '#6B7280',
  divider: isDark ? '#4B5563' : '#E5E7EB',
});


// --- II. সহায়ক ফাংশন (Helper Functions) ---

// Helper function to check if a value is valid
const isValidValue = (value) => {
  if (value === null || value === undefined) return false;
  if (typeof value === 'string') {
    const trimmed = value.trim();
    return trimmed !== '' && trimmed.toLowerCase() !== 'n/a' && trimmed.toLowerCase() !== 'unknown';
  }
  return true;
};

// Helper function to format date in English
const formatDate = (dateString) => {
  if (!dateString) return '';
  try {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  } catch {
    return dateString;
  }
};

// Helper function to format time in English
const formatTime = (dateString) => {
  if (!dateString) return '';
  try {
    const date = new Date(dateString);
    return date.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true
    });
  } catch {
    return new Date().toLocaleTimeString('en-US');
  }
};

// Helper function to format currency
const formatCurrency = (amount) => {
  if (!amount && amount !== 0) return '0.00';
  return new Intl.NumberFormat('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  }).format(amount);
};

// Helper function to get payment method text in English
const getPaymentMethodText = (paymentMethod) => {
  if (!paymentMethod) return 'N/A';
  return PAYMENT_METHODS[paymentMethod] || paymentMethod;
};

// Helper function to get category text in English
const getCategoryText = (category) => {
  if (!category) return 'N/A';
  // If category is an object, extract the name
  if (typeof category === 'object' && category !== null) {
    return category.name || category.label || category.title || 'N/A';
  }
  return CATEGORIES[category] || category;
};

// Helper function to get status text
const getStatusText = (status) => {
  if (!status) return 'N/A';
  const statusMap = {
    'submitted': 'Submitted',
    'pending': 'Pending',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
  };
  return statusMap[status.toLowerCase()] || status;
};


// --- III. HTML বিল্ডিং ফাংশন (Modular HTML Builders) ---

// Common data row builder
const createInfoRow = (label, value, S) => {
    // Always show the row, use N/A if value is invalid
    const displayValue = isValidValue(value) ? value : 'N/A';
    return `<div style="margin: 4px 0; padding: 4px 0; border-bottom: 1px solid ${S.divider}15;">
      <span style="color: ${S.textSecondary}; font-size: 10px; font-weight: 500; text-transform: uppercase; letter-spacing: 0.3px; display: block; margin-bottom: 2px;">${label}</span>
      <span style="color: ${S.textPrimary}; font-size: 12px; font-weight: 600; display: block;">${displayValue}</span>
    </div>`;
};

// 3.1. Header Section
const buildHeaderHTML = (S) => `
    <div style="text-align: center; margin-bottom: 15px; border-bottom: 2px solid ${S.primary}; padding-bottom: 10px;">
      <h1 style="color: ${S.primary}; font-size: 24px; margin: 0 0 6px 0; font-weight: 700; font-family: 'Inter', 'Roboto', 'Arial', sans-serif; letter-spacing: -0.3px;">
        ${L.systemName}
      </h1>
      <p style="color: ${S.textSecondary}; font-size: 11px; margin: 0; font-weight: 500; font-family: 'Inter', 'Roboto', 'Arial', sans-serif; text-transform: uppercase; letter-spacing: 1px;">
        Transaction Receipt
      </p>
    </div>
`;

// 3.2. Summary Section
const buildSummaryHTML = (data, typeData, amount, S) => {
  return `
    <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 15px; padding: 12px; background: ${S.cardBg}; border-radius: 8px; box-shadow: 0 1px 4px rgba(0,0,0,0.1);">
      <div style="flex: 1;">
        <h3 style="color: ${S.textPrimary}; font-size: 14px; margin: 0 0 10px 0; font-weight: 700; font-family: 'Inter', 'Roboto', 'Arial', sans-serif; border-bottom: 2px solid ${S.primary}; padding-bottom: 6px; text-transform: uppercase; letter-spacing: 0.5px;">
          ${L.transactionDetails}
        </h3>
        ${createInfoRow(L.transactionId, data.transactionId || 'N/A', S)}
        ${data.date ? createInfoRow(L.date, formatDate(data.date), S) : ''}
        ${data.date ? createInfoRow(L.time, formatTime(data.date), S) : ''}
        ${createInfoRow(L.transactionType, typeData.text, S)}
        ${data.status ? createInfoRow(L.status, getStatusText(data.status), S) : ''}
        ${createInfoRow(L.createdBy, data.createdBy || 'N/A', S)}
      </div>
      <div style="text-align: right; margin-left: 15px;">
        <div style="background: linear-gradient(135deg, ${typeData.color}15 0%, ${typeData.color}08 100%); padding: 12px 15px; border-radius: 8px; border: 2px solid ${typeData.color}; min-width: 150px; box-shadow: 0 2px 6px ${typeData.color}30;">
          <p style="margin: 0 0 4px 0; color: ${typeData.color}; font-weight: 600; font-size: 10px; font-family: 'Inter', 'Roboto', 'Arial', sans-serif; text-transform: uppercase; letter-spacing: 0.5px;">
            ${typeData.text}
          </p>
          <p style="margin: 0; color: ${S.textPrimary}; font-size: 24px; font-weight: 700; font-family: 'Inter', 'Roboto', 'Arial', sans-serif; letter-spacing: -0.5px;">
            BDT ${formatCurrency(amount)}
          </p>
        </div>
      </div>
    </div>
  `;
};

// 3.3. Customer Information Section
const buildCustomerInfoHTML = (data, S) => {
  // Check for customer info in various possible locations
  const customerName = data.customerName || data.customer?.name || data.partyName || data.party?.name || 'N/A';
  const customerPhone = data.customerPhone || data.customer?.phone || data.party?.phone || data.party?.mobileNumber || 'N/A';
  const customerEmail = data.customerEmail || data.customer?.email || data.party?.email || 'N/A';
  const customerId = data.customerId || data.customer?._id || data.customer?.id || 'N/A';

  return `
    <div style="padding: 12px; background: ${S.cardBg}; border-radius: 8px; border-left: 3px solid ${S.primary}; box-shadow: 0 1px 4px rgba(0,0,0,0.1);">
      <h3 style="color: ${S.textPrimary}; font-size: 13px; margin: 0 0 10px 0; font-weight: 700; font-family: 'Inter', 'Roboto', 'Arial', sans-serif; border-bottom: 2px solid ${S.primary}; padding-bottom: 6px; text-transform: uppercase; letter-spacing: 0.5px;">
        ${L.customerInfo}
      </h3>
      ${createInfoRow(L.name, customerName, S)}
      ${createInfoRow(L.phone, customerPhone, S)}
      ${createInfoRow(L.email, customerEmail, S)}
      ${createInfoRow(L.customerId, customerId, S)}
    </div>
  `;
};

// 3.4. Payment Details Block (Inner part of Payment Info)
const getPaymentDetailsHTML = (paymentDetails, paymentMethod, S) => {
  if (!paymentDetails) return '';

  let detailsHTML = '';
  if (paymentMethod === 'bank') {
    detailsHTML += createInfoRow(L.bankName, paymentDetails.bankName, S);
    detailsHTML += createInfoRow(L.accountNumber, paymentDetails.accountNumber, S);
    detailsHTML += createInfoRow(L.reference, paymentDetails.reference, S);
  } else if (paymentMethod === 'cheque') {
    detailsHTML += createInfoRow(L.chequeNumber, paymentDetails.chequeNumber, S);
    detailsHTML += createInfoRow(L.bankName, paymentDetails.bankName, S);
    detailsHTML += createInfoRow(L.reference, paymentDetails.reference, S);
  } else if (paymentMethod === 'mobile-banking') {
    detailsHTML += createInfoRow(L.mobileProvider, paymentDetails.mobileProvider, S);
    detailsHTML += createInfoRow(L.transactionIdShort, paymentDetails.transactionId, S);
    detailsHTML += createInfoRow(L.reference, paymentDetails.reference, S);
  } else if (paymentMethod === 'cash') {
    detailsHTML += createInfoRow(L.reference, paymentDetails.reference, S);
  }
  return detailsHTML;
};

// 3.5. Payment Information Section
const buildPaymentInfoHTML = (data, S) => {
  const hasPaymentInfo = isValidValue(data.paymentMethod) || isValidValue(data.category) || (data.paymentDetails && Object.keys(data.paymentDetails).some(key => key !== 'amount' && isValidValue(data.paymentDetails[key])));
  
  if (!hasPaymentInfo) return '';

  const paymentMethodText = getPaymentMethodText(data.paymentMethod);
  const categoryText = getCategoryText(data.category);

  return `
    <div style="padding: 12px; background: ${S.cardBg}; border-radius: 8px; border-left: 3px solid ${S.secondary}; box-shadow: 0 1px 4px rgba(0,0,0,0.1);">
      <h3 style="color: ${S.textPrimary}; font-size: 13px; margin: 0 0 10px 0; font-weight: 700; font-family: 'Inter', 'Roboto', 'Arial', sans-serif; border-bottom: 2px solid ${S.secondary}; padding-bottom: 6px; text-transform: uppercase; letter-spacing: 0.5px;">
        ${L.paymentInfo}
      </h3>
      ${createInfoRow(L.paymentMethod, paymentMethodText, S)}
      ${createInfoRow(L.category, categoryText, S)}
      ${getPaymentDetailsHTML(data.paymentDetails, data.paymentMethod, S)}
    </div>
  `;
};

// 3.6. Bank Transfer Information Section
const buildBankTransferInfoHTML = (data, S) => {
  const debitAccount = data.debitAccount || data.sourceAccount;
  const creditAccount = data.creditAccount || data.destinationAccount;
  const paymentMethod = data.paymentMethod;
  const paymentDetails = data.paymentDetails;
  
  // Check if it's a cash transaction
  const isCash = paymentMethod === 'cash' || paymentMethod === 'নগদ' || !debitAccount && !creditAccount;
  
  // Check if it's an account transfer
  const isAccountTransfer = debitAccount && creditAccount;
  
  // Check if it's a bank transfer (has payment details with bank info)
  const hasBankInfo = paymentDetails && (paymentDetails.bankName || paymentDetails.accountNumber);
  
  if (isCash && !hasBankInfo && !isAccountTransfer) {
    // Cash transaction
    return `
      <div style="margin-bottom: 12px; padding: 12px; background: ${S.cardBg}; border-radius: 8px; border-left: 3px solid ${S.warning}; box-shadow: 0 1px 4px rgba(0,0,0,0.1);">
        <h3 style="color: ${S.textPrimary}; font-size: 13px; margin: 0 0 10px 0; font-weight: 700; font-family: 'Inter', 'Roboto', 'Arial', sans-serif; border-bottom: 2px solid ${S.warning}; padding-bottom: 6px; text-transform: uppercase; letter-spacing: 0.5px;">
          Transaction Method
        </h3>
        <div style="padding: 10px; background: ${S.bg}; border-radius: 6px; border: 2px solid ${S.warning}; text-align: center;">
          <p style="color: ${S.textPrimary}; font-size: 16px; font-weight: 700; margin: 0; font-family: 'Inter', 'Roboto', 'Arial', sans-serif;">
            💵 Cash Transaction
          </p>
          ${paymentDetails?.reference ? createInfoRow('Reference', paymentDetails.reference, S) : ''}
        </div>
      </div>
    `;
  }
  
  if (isAccountTransfer) {
    // Account to Account Transfer
    const fromBank = debitAccount.bankName || 'N/A';
    const fromAccount = debitAccount.accountNumber || 'N/A';
    const fromName = debitAccount.name || 'N/A';
    const toBank = creditAccount.bankName || 'N/A';
    const toAccount = creditAccount.accountNumber || 'N/A';
    const toName = creditAccount.name || 'N/A';
    
    return `
      <div style="margin-bottom: 12px; padding: 12px; background: ${S.cardBg}; border-radius: 8px; border-left: 3px solid ${S.info}; box-shadow: 0 1px 4px rgba(0,0,0,0.1);">
        <h3 style="color: ${S.textPrimary}; font-size: 13px; margin: 0 0 10px 0; font-weight: 700; font-family: 'Inter', 'Roboto', 'Arial', sans-serif; border-bottom: 2px solid ${S.info}; padding-bottom: 6px; text-transform: uppercase; letter-spacing: 0.5px;">
          Bank Transfer Details
        </h3>
        <div style="display: grid; grid-template-columns: 1fr auto 1fr; gap: 10px; align-items: center;">
          <div style="padding: 10px; background: ${S.bg}; border-radius: 6px; border: 2px solid ${S.primary};">
            <h4 style="color: ${S.textPrimary}; font-size: 11px; margin: 0 0 8px 0; font-weight: 600; font-family: 'Inter', 'Roboto', 'Arial', sans-serif; text-transform: uppercase; letter-spacing: 0.3px; color: ${S.primary};">
              From Account
            </h4>
            ${createInfoRow('Account Name', fromName, S)}
            ${createInfoRow('Bank Name', fromBank, S)}
            ${createInfoRow('Account Number', fromAccount, S)}
          </div>
          <div style="text-align: center;">
            <div style="width: 30px; height: 30px; background: ${S.info}; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 0 auto;">
              <span style="color: white; font-size: 16px; font-weight: bold;">→</span>
            </div>
          </div>
          <div style="padding: 10px; background: ${S.bg}; border-radius: 6px; border: 2px solid ${S.secondary};">
            <h4 style="color: ${S.textPrimary}; font-size: 11px; margin: 0 0 8px 0; font-weight: 600; font-family: 'Inter', 'Roboto', 'Arial', sans-serif; text-transform: uppercase; letter-spacing: 0.3px; color: ${S.secondary};">
              To Account
            </h4>
            ${createInfoRow('Account Name', toName, S)}
            ${createInfoRow('Bank Name', toBank, S)}
            ${createInfoRow('Account Number', toAccount, S)}
          </div>
        </div>
        ${paymentDetails?.reference ? `<div style="margin-top: 10px; padding-top: 10px; border-top: 1px solid ${S.divider};">${createInfoRow('Reference', paymentDetails.reference, S)}</div>` : ''}
      </div>
    `;
  }
  
  // Single bank transaction (debit or credit with bank details)
  if (hasBankInfo || debitAccount || creditAccount) {
    const account = debitAccount || creditAccount;
    const accountType = debitAccount ? 'Debit Account' : 'Credit Account';
    const bankName = account?.bankName || paymentDetails?.bankName || 'N/A';
    const accountNumber = account?.accountNumber || paymentDetails?.accountNumber || 'N/A';
    const accountName = account?.name || 'N/A';
    
    return `
      <div style="margin-bottom: 12px; padding: 12px; background: ${S.cardBg}; border-radius: 8px; border-left: 3px solid ${S.info}; box-shadow: 0 1px 4px rgba(0,0,0,0.1);">
        <h3 style="color: ${S.textPrimary}; font-size: 13px; margin: 0 0 10px 0; font-weight: 700; font-family: 'Inter', 'Roboto', 'Arial', sans-serif; border-bottom: 2px solid ${S.info}; padding-bottom: 6px; text-transform: uppercase; letter-spacing: 0.5px;">
          Bank Information
        </h3>
        <div style="padding: 10px; background: ${S.bg}; border-radius: 6px; border: 2px solid ${S.info};">
          <h4 style="color: ${S.textPrimary}; font-size: 11px; margin: 0 0 8px 0; font-weight: 600; font-family: 'Inter', 'Roboto', 'Arial', sans-serif; text-transform: uppercase; letter-spacing: 0.3px; color: ${S.info};">
            ${accountType}
          </h4>
          ${createInfoRow('Account Name', accountName, S)}
          ${createInfoRow('Bank Name', bankName, S)}
          ${createInfoRow('Account Number', accountNumber, S)}
          ${paymentDetails?.reference ? createInfoRow('Reference', paymentDetails.reference, S) : ''}
        </div>
      </div>
    `;
  }
  
  return '';
};


// 3.7. Footer Section
const buildFooterHTML = (S) => `
    <div style="margin-top: 15px; padding-top: 10px; border-top: 1px solid ${S.divider}; text-align: center;">
      <p style="color: ${S.textSecondary}; font-size: 9px; margin: 0 0 4px 0; font-family: 'Inter', 'Roboto', 'Arial', sans-serif; font-style: italic;">
        ${L.footerMessage}
      </p>
      <p style="color: ${S.textSecondary}; font-size: 8px; margin: 0; font-family: 'Inter', 'Roboto', 'Arial', sans-serif;">
        Generated on ${new Date().toLocaleString('en-US', { dateStyle: 'short', timeStyle: 'short' })} | ${L.systemName}
      </p>
    </div>
`;

// --- IV. মূল রিসিট জেনারেটর (Main Receipt Generator) ---

// Create HTML element for receipt
const createReceiptElement = (transactionData, isDark) => {
  const S = getStyles(isDark); // Get styles based on theme
  
  const receiptDiv = document.createElement('div');
  receiptDiv.style.cssText = `
    position: absolute;
    top: -9999px;
    left: -9999px;
    width: 750px;
    padding: 25px;
    background: ${S.bg};
    color: ${S.textPrimary};
    font-family: 'Inter', 'Roboto', 'Arial', sans-serif;
    line-height: 1.3;
  `;

  const typeKey = transactionData.transactionType && TRANSACTION_TYPES[transactionData.transactionType] 
                    ? transactionData.transactionType 
                    : 'account-transfer';
  const typeData = TRANSACTION_TYPES[typeKey];
  const amount = transactionData.paymentDetails?.amount || transactionData.amount || 0;

  // Build modular HTML sections
  const headerHTML = buildHeaderHTML(S);
  const summaryHTML = buildSummaryHTML(transactionData, typeData, amount, S);
  const customerInfoHTML = buildCustomerInfoHTML(transactionData, S);
  const paymentInfoHTML = buildPaymentInfoHTML(transactionData, S);
  const bankTransferInfoHTML = buildBankTransferInfoHTML(transactionData, S);
  const footerHTML = buildFooterHTML(S);

  receiptDiv.innerHTML = `
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    ${headerHTML}
    ${summaryHTML}
    
    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 15px;">
      ${customerInfoHTML}
      ${paymentInfoHTML}
    </div>

    ${bankTransferInfoHTML}
    ${footerHTML}
  `;

  return receiptDiv;
};

// Generate PDF for transaction receipt (unchanged from original logic)
export const generateTransactionPDF = async (transactionData, isDark = false) => {
  try {
    // 1. Create a temporary element to render the receipt
    const receiptElement = createReceiptElement(transactionData, isDark);
    document.body.appendChild(receiptElement);

    // 2. Generate canvas from HTML element (reduced scale to fit on one page)
    const canvas = await html2canvas(receiptElement, {
      scale: 1.5,
      useCORS: true,
      allowTaint: true,
      backgroundColor: isDark ? '#1F2937' : '#FFFFFF',
      logging: false
    });

    // 3. Remove temporary element
    document.body.removeChild(receiptElement);

    // 4. Create PDF
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    
    const imgWidth = 210; // A4 width in mm
    const pageHeight = 295; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;

    let position = 0;

    // Add image to PDF
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    // Add new page if content is longer than one page
    while (heightLeft >= -1) { // -1 to handle minor rounding issues
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    // 5. Generate filename and Download PDF
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `transaction_${transactionData.transactionId || 'receipt'}_${timestamp}.pdf`;

    pdf.save(filename);
    
    return { success: true, filename };
  } catch (error) {
    console.error('PDF generation error:', error);
    return { success: false, error: error.message };
  }
};

// Simple PDF generator as fallback (text-based, no HTML rendering)
export const generateSimplePDF = (transactionData) => {
  try {
    const pdf = new jsPDF('p', 'mm', 'a4');
    
    // Header
    pdf.setFontSize(20);
    pdf.setTextColor(59, 130, 246); // Blue
    pdf.text(L.systemName, 105, 20, { align: 'center' });
    
    pdf.setFontSize(14);
    pdf.setTextColor(107, 114, 128); // Gray
    pdf.text('Transaction Receipt', 105, 30, { align: 'center' });
    
    // Transaction Details
    let yPos = 50;
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    
    pdf.setFont(undefined, 'bold');
    pdf.text('Transaction ID:', 20, yPos);
    pdf.setFont(undefined, 'normal');
    pdf.text(transactionData.transactionId || 'N/A', 70, yPos);
    yPos += 10;
    
    if (transactionData.date) {
      pdf.setFont(undefined, 'bold');
      pdf.text('Date:', 20, yPos);
      pdf.setFont(undefined, 'normal');
      pdf.text(formatDate(transactionData.date), 70, yPos);
      yPos += 10;
    }
    
    pdf.setFont(undefined, 'bold');
    pdf.text('Type:', 20, yPos);
    pdf.setFont(undefined, 'normal');
    const typeText = transactionData.transactionType === 'credit' ? 'Credit (Income)' : 
                     transactionData.transactionType === 'debit' ? 'Debit (Expense)' : 
                     'Account Transfer';
    pdf.text(typeText, 70, yPos);
    yPos += 10;
    
    const amount = transactionData.paymentDetails?.amount || transactionData.amount || 0;
    pdf.setFont(undefined, 'bold');
    pdf.text('Amount:', 20, yPos);
    pdf.setFont(undefined, 'normal');
    pdf.text(`BDT ${formatCurrency(amount)}`, 70, yPos);
    yPos += 15;
    
    // Customer Information
    pdf.setFont(undefined, 'bold');
    pdf.setFontSize(14);
    pdf.text('Customer Information', 20, yPos);
    yPos += 10;
    
    pdf.setFontSize(11);
    pdf.setFont(undefined, 'normal');
    const customerName = transactionData.customerName || transactionData.customer?.name || 'N/A';
    pdf.text(`Name: ${customerName}`, 25, yPos);
    yPos += 8;
    
    const customerPhone = transactionData.customerPhone || transactionData.customer?.phone || 'N/A';
    pdf.text(`Phone: ${customerPhone}`, 25, yPos);
    yPos += 8;
    
    const customerEmail = transactionData.customerEmail || transactionData.customer?.email || 'N/A';
    pdf.text(`Email: ${customerEmail}`, 25, yPos);
    yPos += 15;
    
    // Payment Information
    pdf.setFont(undefined, 'bold');
    pdf.setFontSize(14);
    pdf.text('Payment Information', 20, yPos);
    yPos += 10;
    
    pdf.setFontSize(11);
    pdf.setFont(undefined, 'normal');
    const paymentMethod = getPaymentMethodText(transactionData.paymentMethod);
    pdf.text(`Payment Method: ${paymentMethod}`, 25, yPos);
    yPos += 8;
    
    const category = getCategoryText(transactionData.category);
    pdf.text(`Category: ${category}`, 25, yPos);
    yPos += 15;
    
    // Bank Transfer Information
    const debitAccount = transactionData.debitAccount || transactionData.sourceAccount;
    const creditAccount = transactionData.creditAccount || transactionData.destinationAccount;
    
    if (debitAccount && creditAccount) {
      pdf.setFont(undefined, 'bold');
      pdf.setFontSize(14);
      pdf.text('Bank Transfer Details', 20, yPos);
      yPos += 10;
      
      pdf.setFontSize(11);
      pdf.setFont(undefined, 'normal');
      pdf.text(`From: ${debitAccount.bankName || 'N/A'} - ${debitAccount.accountNumber || 'N/A'}`, 25, yPos);
      yPos += 8;
      pdf.text(`To: ${creditAccount.bankName || 'N/A'} - ${creditAccount.accountNumber || 'N/A'}`, 25, yPos);
      yPos += 10;
    } else if (debitAccount || creditAccount) {
      const account = debitAccount || creditAccount;
      pdf.setFont(undefined, 'bold');
      pdf.setFontSize(14);
      pdf.text('Bank Information', 20, yPos);
      yPos += 10;
      
      pdf.setFontSize(11);
      pdf.setFont(undefined, 'normal');
      pdf.text(`Bank: ${account.bankName || 'N/A'}`, 25, yPos);
      yPos += 8;
      pdf.text(`Account: ${account.accountNumber || 'N/A'}`, 25, yPos);
      yPos += 10;
    } else if (transactionData.paymentMethod === 'cash') {
      pdf.setFont(undefined, 'bold');
      pdf.setFontSize(14);
      pdf.text('Transaction Method', 20, yPos);
      yPos += 10;
      
      pdf.setFontSize(11);
      pdf.setFont(undefined, 'normal');
      pdf.text('Cash Transaction', 25, yPos);
      yPos += 10;
    }
    
    // Footer
    pdf.setFontSize(10);
    pdf.setTextColor(107, 114, 128);
    pdf.text(L.footerMessage, 105, 280, { align: 'center' });
    pdf.text(`Generated on ${new Date().toLocaleString('en-US')}`, 105, 285, { align: 'center' });
    
    // Generate filename and save
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `transaction_${transactionData.transactionId || 'receipt'}_${timestamp}.pdf`;
    pdf.save(filename);
    
    return { success: true, filename };
  } catch (error) {
    console.error('Simple PDF generation error:', error);
    return { success: false, error: error.message };
  }
};